### ISSUE TITLE
2023-09-04 MON

### ISSUE THREAD

**Issue by honghyunshik** [honghyunshik/study-record#2]
### 부동 소수점 오차
https://www.notion.so/3c900e0da662463d9bbfb5fe2dfc810e?v=237afe82004043f283b5ded9718a5cf3&p=f396676ddaed4e56aba8e12ef596ef77&pm=c

### DNS
https://www.notion.so/3c900e0da662463d9bbfb5fe2dfc810e?v=237afe82004043f283b5ded9718a5cf3&p=04991883779645cbb6f3dbeccf7e0b1d&pm=c

## 알고리즘

DP + 누적합

https://github.com/honghyunshik/Algorithm/tree/main/%EB%B0%B1%EC%A4%80/Gold/1915.%E2%80%85%EA%B0%80%EC%9E%A5%E2%80%85%ED%81%B0%E2%80%85%EC%A0%95%EC%82%AC%EA%B0%81%ED%98%95

### 2차원 배열의 누적합 구하기
dp[i][j] = dp[i-1][j] + dp[i][j-1] - dp[i-1][j-1] + board[i][j]
혹은
board[i][j] += board[i-1][j] + board[i][j-1] - board[i-1][j-1] 

### 정사각형의 최대 넓이 구하기 
1. 누적합을 통해 DP 배열 생성
2. i,j 의 부분합과 i+dis, j+dis 의 부분합의 차이를 통해 정사각형 여부 판단 가능

### 내일 풀거
https://www.acmicpc.net/problem/1028
https://www.acmicpc.net/problem/1039

**Comment by Kim-Jin-Uk** [comment]
DNS 내용은 비어있는데 확인 한번 해줘

**Comment by honghyunshik** [comment]
> DNS 내용은 비어있는데 확인 한번 해줘 알고리즘도 private인지 나한테는 안보이네 프로젝트도 가급적 매일할 수 있도록 하면 좋을듯 알고리즘은 하루 한문제만 하고
> 
> 너 스스로 만족할 수 있을만큼 공부해 아직까지는 내가봤을때는 공부량이 많지는 않은 것 같아

DNS는 아직 하는중이고 알고리즘은 public으로 바꿔놓을게
