### ISSUE TITLE
2023-09-08 FRI

### ISSUE THREAD

**Issue by honghyunshik** [honghyunshik/study-record#5]
## CS

그래프 탐색 알고리즘(BFS, DFS,다익스트라, 벨만포드, 플루이드 워셜)
14:30~18:30
https://www.notion.so/1425903afbe74725944c09fb2f4480e1
구현
https://github.com/honghyunshik/Algorithm/tree/main/shortestPath

탐색 알고리즘(선형, 이진, 해시)
18:30~
https://www.notion.so/f146f7f095fe4d008b7611db4d6dcb37

## 알고리즘

BigInteger + Greedy
12:00~14:30
https://github.com/honghyunshik/Algorithm/tree/main/%EB%B0%B1%EC%A4%80/Gold/1036.%E2%80%8536%EC%A7%84%EC%88%98
BigInteger에 익숙하지 않아서 a.add(b) 값을 a에다가 다시 넣어줘야 하는것을 실수해 오래걸렸다..

**Comment by Kim-Jin-Uk** [comment]
코드에 간략하게라도 주석이 있으면 내가 해석하는데 도움이 될것 같음

**Comment by Kim-Jin-Uk** [comment]
DFS 에서 재귀함수를 이용하는 방식, 스택을 이용하는 방식의 장단점은 뭘까?

**Comment by Kim-Jin-Uk** [comment]
해시 탐색에도 시간복잡도에 대한 설명이 추가되어야 할 것 같음
