### ISSUE TITLE
2023-09-11

### ISSUE THREAD

**Issue by honghyunshik** [honghyunshik/study-record#6]
## CS

문자열 검색 알고리즘
https://www.notion.so/f47e71fa536a43da8d5d6ff2feaf4515

## 알고리즘

Union-Find?
https://www.notion.so/LV-4-68c74193e73543be82ae1f1cc8fe8505
https://github.com/honghyunshik/Algorithm/tree/main/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/lv4/64063.%E2%80%85%ED%98%B8%ED%85%94%E2%80%85%EB%B0%A9%E2%80%85%EB%B0%B0%EC%A0%95

Trie
https://www.notion.so/3-LV4-a3042479b215408a870aec90adb2c80b

## 프로젝트 진행상황

플러그인 다운로드 + 사용자 이름 변경
https://www.notion.so/The-IDE-failed-to-install-or-update-some-plugins-bd8204ee00b2475ca0caefdc03240dc1

elastic search https 요청 + 인증서 만료 문제
https://www.notion.so/Elastic-Search-2-b5da51a9a023414c861d1b35faffce47

**Comment by Kim-Jin-Uk** [comment]
프로젝트가 좀 진행되면 좋겠네

**Comment by Kim-Jin-Uk** [comment]
union find 알고리즘의 경우에는 union find rank 기법이랑 path compression 기법 통해서 개선이 가능하니 추가 학습해봐

**Comment by Kim-Jin-Uk** [comment]
현재는 알고리즘 위주의 CS 학습이 주를 이루고 있는데 다른 부분도 학습 진행해줘

**Comment by honghyunshik** [comment]
> 현재는 알고리즘 위주의 CS 학습이 주를 이루고 있는데 다른 부분도 학습 진행해줘

자료구조/알고리즘 끝내고 딴거할라고 하긴 했었는데
