### ISSUE TITLE
2023-09-12 RECORD

### ISSUE THREAD

**Issue by honghyunshik** [honghyunshik/study-record#7]
## CS

[Entity와 DTO를 분리하는 이유](https://www.notion.so/Entity-DTO-ec289346fa374350a3ea0211d3a83e88)

[직렬화, 역직렬화](https://www.notion.so/Serialization-7b64d1c7a0734833a18702798b09377c)

## 알고리즘

Trie 카카오 2018 블라인드 테스트
[정리](https://www.notion.so/3-LV4-a3042479b215408a870aec90adb2c80b)  [깃허브](https://github.com/honghyunshik/Algorithm/blob/main/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/lv4/%5B3%EC%B0%A8%5D%20%EC%9E%90%EB%8F%99%EC%99%84%EC%84%B1.java)
Trie 자료구조가 익숙하지 않아서 좀 헷갈렸다...

**Comment by Kim-Jin-Uk** [comment]
entity, dto는 repository랑도 많이 비교되고 있어서 repository와는 어떤 부분에 차이가 존재하는지도 기술하면 좋을 것 같아

**Comment by Kim-Jin-Uk** [comment]
질문이 있으면 멘션도 가능하니 참고해
